export const widgetsData = {
    asistencia: { icon: '📋', title: 'Control de Asistencia', description: 'Lleva un registro diario de la asistencia, asigna insignias por buen comportamiento y registra alertas.' },
    calculadora: { icon: '🧮', title: 'Calculadora Científica', description: 'Realiza operaciones matemáticas complejas, incluyendo funciones trigonométricas, logaritmos y más.' },
    calendario: { icon: '📅', title: 'Calendario', description: 'Consulta fechas rápidamente con este simple calendario mensual.' },
    carrusel: { icon: '🖼️', title: 'Carrusel de Imágenes', description: 'Carga tus propias imágenes para mostrarlas en una presentación de diapositivas.' },
    conversor: { icon: '🔄', title: 'Conversor de Unidades', description: 'Convierte fácilmente entre diferentes unidades de longitud, peso y temperatura.' },
    cronometro: { icon: '⏱️', title: 'Cronómetro', description: 'Mide el tiempo con precisión y registra vueltas (laps) para tus actividades.' },
    dados: { icon: '🎲', title: 'Dados 3D', description: 'Lanza uno o varios dados virtuales con una divertida animación en tres dimensiones.' },
    grupos: { icon: '👥', title: 'Generador de Grupos', description: 'Crea grupos de trabajo aleatorios a partir de una lista de nombres.' },
    qr: { icon: '🔲', title: 'Generador QR', description: 'Crea un código QR a partir de cualquier texto o URL para compartirlo fácilmente.' },
    gestos: { icon: '✋', title: 'Gestos de Trabajo', description: 'Muestra tarjetas visuales para indicar el modo de trabajo: Silencio, Parejas, Equipos, etc.' },
    html: { icon: '🚀', title: 'HTML Sandbox', description: 'Un espacio para pegar código HTML y ver una vista previa al instante.' },
    latex: { icon: '📜', title: 'Intérprete MD/LaTeX', description: 'Renderiza texto en formato Markdown junto con fórmulas matemáticas en LaTeX.' },
    lista: { icon: '✅', title: 'Lista de Trabajo', description: 'Un práctico gestor de tareas (to-do list) para organizar las actividades del día.' },
    marcador: { icon: '🏆', title: 'Marcador de Puntos', description: 'Lleva la puntuación de varios equipos o jugadores durante una competición.' },
    ruido: { icon: '🔊', title: 'Medidor de Ruido', description: 'Usa el micrófono para medir el nivel de ruido y ayudar a gestionar el ambiente en el aula.' },
    memorama: { icon: '🧠', title: 'Memorama', description: 'Crea un juego de memoria personalizado cargando tus propias imágenes.' },
    metronomo: { icon: '🎼', title: 'Metrónomo', description: 'Marca un tempo constante (BPM) para actividades rítmicas o musicales.' },
    notas: { icon: '📝', title: 'Bloc de Notas', description: 'Un editor de texto enriquecido para tomar apuntes rápidos con formato.' },
    puzzle: { icon: '🧩', title: 'Puzzle Deslizante', description: 'Convierte cualquier imagen en un clásico puzzle deslizante para resolver.' },
    relojes: { icon: '🌍', title: 'Relojes Mundiales', description: 'Muestra la hora actual en diferentes ciudades del mundo.' },
    ruleta: { icon: '🎡', title: 'Ruleta Aleatoria', description: 'Una ruleta personalizable para seleccionar nombres u opciones al azar.' },
    semaforo: { icon: '🚦', title: 'Semáforo', description: 'Un semáforo visual para gestionar tiempos o niveles de ruido en el aula.' },
    temporizador: { icon: '⏳', title: 'Temporizador', description: 'Un contador regresivo ideal para controlar el tiempo de las actividades.' },
    tictactoe: { icon: '⭕', title: 'Tic-Tac-Toe', description: 'El clásico juego de tres en raya para dos jugadores.' },
    visor: { icon: '🌐', title: 'Visor Web', description: 'Embebe y muestra el contenido de cualquier página web directamente en el escritorio.' },
};
